# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        general:
            language: fr       # Langue de l'éditeur
            toolbar: standard  # type de toolbar (basic / standard / full)
            uicolor: "#5bc0de" # Couleur de fond de l'éditeur
            height: 200px      # hauteur de l'éditeur
