# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

fos_ck_editor:
    configs:
        main_config:
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike', 'Blockquote',
                 '-', 'Link', '-', 'RemoveFormat', '-', 'NumberedList', 'BulletedList', '-',
                  'Outdent', 'Indent', '-', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight',
                  'JustifyBlock', '-', 'Image', 'Table', 'Smiley', '-', 'Styles', 'Format','Font','FontSize',
                  '-', 'TextColor', 'BGColor', 'Source', 'Checkbox', 'Preview'] }

        general:
            language: fr       # Langue de l'éditeur
            # toolbar: standard  # type de toolbar (basic / standard / full)
            uicolor: "#adb5bd" # Couleur de fond de l'éditeur
            height: 300px      # hauteur de l'éditeur
            width: 800px       # largeur de l'éditeur

        my_config:
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike', 'Blockquote',
                 '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight',
                  'JustifyBlock', '-', 'Smiley', '-', 'Styles', 'Format','Font','FontSize',
                  '-', 'TextColor', 'BGColor'] }

            language: fr       # Langue de l'éditeur
            # toolbar: basic     # type de toolbar (basic / standard / full)
            uicolor: "#adb5bd" # Couleur de fond de l'éditeur
            height: 300px      # hauteur de l'éditeur
            width: 800px       # largeur de l'éditeur

        config_phone:
            toolbar:
                - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike', 'Blockquote',
                 '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight',
                  'JustifyBlock', '-', 'Smiley', '-', 'Styles', 'Format','Font','FontSize',
                  '-', 'TextColor', 'BGColor'] }

            language: fr       # Langue de l'éditeur
            uicolor: "#adb5bd" # Couleur de fond de l'éditeur
            height: 300px      # hauteur de l'éditeur
            width: 600px       # largeur de l'éditeur