twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_horizontal_layout.html.twig']
        # 'form/custom_types.html.twig'

    globals:
        # Récupération du nom du site dans le fichier services.yaml
        site_name: '%app.site_name%'
        # Récupération de la clé publique Google Recaptcha depuis le fichier services.yaml
        # google_recaptcha_site_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY%'
when@test:
    twig:
        strict_variables: true